### ISSUE TITLE
hipsparseLtGetProperty cant use

### ISSUE THREAD

**Issue by S-hhhhh** [ROCmSoftwarePlatform/hipSPARSELt#157]
https://github.com/ROCm/hipSPARSELt/blob/8473af4ba4bde579fbf9854bac630ea0598f1d7f/library/src/hcc_detail/hipsparselt.cpp#L1008
![image](https://github.com/user-attachments/assets/62a728fd-2cc7-4fff-bd1e-693eda630549)

**Comment by harkgill-amd** [comment]
Thanks for pointing this out @S-hhhhh. The typo in `hipsparseLtGetProperty` is fixed in https://github.com/ROCm/hipSPARSELt/commit/16d3052ec6129bc25b32b484e3afdbb42079bef6.
