### ISSUE TITLE
Meanings of the variables 

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/hipSPARSELt#70]
Could you please explain the meanings of the following variables in https://github.com/ROCm/hipSPARSELt/blob/develop/clients/samples/example_compress.cpp ?  Thanks.

                       stride_2,
                       stride_1,
                       stride,
                       c_stride_2,
                       c_stride_1,
                       c_stride_b,
                       m_stride_2,
                       m_stride_1,
                       m_stride_b,

**Comment by ppanchad-amd** [comment]
Hi @jinz2014, internal ticket has been created to assist with your question. Thanks!

**Comment by jamesxu2** [comment]
Hi @jinz2014 , here is the response from the hipSPARSELt team:

>  Here is the document of compress function's API. 
[hipSPARSELt: Helper functions — hipSPARSELt 0.2.1 Documentation (amd.com)](https://rocm.docs.amd.com/projects/hipSPARSELt/en/latest/doxygen/html/group__helper__module.html#ga982409bdcd64904075904c6e53a2fb16)

> Those variables are strides for the matrix on M and N dimension, we use strides to determine the Matrix's layout (how to access this matrix in the memory).
For example, a MxN non-transpose matrix, in the general case, which stride1 will be 1 and which stride2 will be the leading dimension (usually is M).
 
> And the c_stride1,2 are strides for compressed matrix, and the m_stride1,2 are for metadata matrix.
 
> we can see how to get those values at [L645-L675](https://github.com/ROCm/hipSPARSELt/blob/develop/clients/samples/example_compress.cpp#L635-L675)
 
> For users, when they are using this compress function. [you] don't need to know c_stride1,2 and m_striDe1,2, those are automatically derived inside the hipsparselt library (a black box for user). And those variables in this sample are only used for validation.
> [You] only need to provide the Matrix's Row, Column and Leading dimension to the API,  you can see how to set those values and use the compress function at [L718-L829](https://github.com/ROCm/hipSPARSELt/blob/develop/clients/samples/example_compress.cpp#L718-L829)

**Comment by jinz2014** [comment]
Thanks!
